/**
 * Music Session — the "say what you want to make" engine.
 *
 * Replaces the old static nine-row beginner checklist. The interaction is
 * modeled on how the owner actually works with ChatGPT and Claude: say the
 * goal, get ONE next move, copy it somewhere useful, do the work, paste back
 * what happened, keep going. No AI call happens here — every move is a
 * deterministic template built from the goal text, the chosen tool, and
 * whatever the creator pasted back last. Nothing here is generated by a
 * model, and nothing here claims to be.
 *
 * Pure functions only — persistence lives in music-session.store.ts, UI in
 * MusicSession.tsx.
 */

// ---------------------------------------------------------------------------
// Tools — kept lightweight on purpose. "Not sure yet" is a valid answer.
// ---------------------------------------------------------------------------

export type Tool =
  | "bandlab" | "garageband" | "ableton" | "fl-studio"
  | "logic" | "ardour" | "mpc" | "other" | "unsure";

export const TOOL_LABELS: Record<Tool, string> = {
  bandlab: "BandLab",
  garageband: "GarageBand",
  ableton: "Ableton",
  "fl-studio": "FL Studio",
  logic: "Logic",
  ardour: "Ardour",
  mpc: "MPC",
  other: "Other",
  unsure: "Not sure yet",
};

export const TOOLS = Object.keys(TOOL_LABELS) as Tool[];

// ---------------------------------------------------------------------------
// Stages — the subtle progress rail. Six stages, seven moves (Finish holds two).
// ---------------------------------------------------------------------------

export type MusicStage = "idea" | "groove" | "bass" | "music" | "arrange" | "finish";

export const STAGE_LABELS: Record<MusicStage, string> = {
  idea: "Idea",
  groove: "Groove",
  bass: "Bass",
  music: "Music",
  arrange: "Arrange",
  finish: "Finish",
};

export const STAGE_ORDER: MusicStage[] = ["idea", "groove", "bass", "music", "arrange", "finish"];

// ---------------------------------------------------------------------------
// Profile detection — a small number of sensible pathways, not a genre engine.
// ---------------------------------------------------------------------------

export type Profile = "reggae" | "hiphop" | "piano" | "ambient" | "existing-idea" | "generic";

export function detectProfile(goal: string): Profile {
  const g = goal.toLowerCase();
  if (/reggae|dub\b|one.?drop|\bska\b/.test(g)) return "reggae";
  if (/hip.?hop|\btrap\b|boom.?bap|\brap\b/.test(g)) return "hiphop";
  if (/\bpiano\b|solo keys|keys idea/.test(g)) return "piano";
  if (/\bgame\b|background music|\bambient\b|\bscore\b|underscore/.test(g)) return "ambient";
  if (/already (have|started|wrote|working)|half.?finished|existing (idea|song)|idea i (already )?have/.test(g)) return "existing-idea";
  return "generic";
}

// ---------------------------------------------------------------------------
// Moves — one deterministic next step at a time.
// ---------------------------------------------------------------------------

export interface Move {
  index: number;
  stage: MusicStage;
  title: string;
  detail: string;
  copyText: string;
}

export const TOTAL_MOVES = 7;

function toolPrefix(tool: Tool): string {
  return tool === "unsure" ? "In your music app, " : `In ${TOOL_LABELS[tool]}, `;
}

function toolFor(tool: Tool): string {
  return tool === "unsure" ? "in my music app (I haven't picked one yet)" : `in ${TOOL_LABELS[tool]}`;
}

function goalSentence(goal: string): string {
  return goal.trim() ? `I'm working on: "${goal.trim()}".` : "I'm making my first beat.";
}

function assistantPrompt(ctx: { goal: string; tool: Tool; lastNote?: string }, task: string): string {
  const note = ctx.lastNote?.trim();
  const notePart = note ? ` Last update: ${note}${/[.!?]$/.test(note) ? "" : "."}` : "";
  return `Help me ${task} ${toolFor(ctx.tool)}. ${goalSentence(ctx.goal)}${notePart} Give me only the next small step. Keep it beginner-friendly.`;
}

interface ProfileContent {
  groove: { title: string; detail: string; task: string };
  bass: { title: string; detail: string; task: string };
  music: { title: string; detail: string; task: string };
}

const PROFILE_CONTENT: Record<Profile, ProfileContent> = {
  reggae: {
    groove: {
      title: "Set up a one-drop groove",
      detail: "Kick and snare land together on beat 3. Hi-hats sit on the off-beats — the \"and\" of each beat, not the beat itself.",
      task: "set up a one-drop reggae groove — kick and snare together on beat 3, hi-hats on the off-beats",
    },
    bass: {
      title: "Add a reggae bassline",
      detail: "A simple, syncopated bass that leans into the off-beat and leaves space around the one-drop. Two or three repeating notes is enough.",
      task: "add a simple syncopated reggae bassline that follows the one-drop groove",
    },
    music: {
      title: "Add the skank",
      detail: "A short chord stab (guitar or keys) on the off-beats is the classic reggae skank. Keep it short and let it breathe.",
      task: "add a reggae guitar or keys skank on the off-beats",
    },
  },
  hiphop: {
    groove: {
      title: "Set up a boom-bap groove",
      detail: "Kick on beat 1 and the \"and\" of beat 2, snare on 2 and 4, hats in a swung pattern underneath.",
      task: "set up a boom-bap hip-hop drum pattern — kick on 1 and the and-of-2, snare on 2 and 4, swung hats",
    },
    bass: {
      title: "Add an 808 or bass line",
      detail: "A bass that slides between two or three notes, sitting right under the kick. Let it breathe between hits.",
      task: "add a simple 808-style bass line that sits under the kick",
    },
    music: {
      title: "Add a loop or one melodic sample",
      detail: "One sample, loop, or simple keys line on top is enough for a first idea. Keep it repetitive on purpose.",
      task: "add one melodic loop or sample on top of the beat",
    },
  },
  piano: {
    groove: {
      title: "Play a simple chord progression",
      detail: "Skip the drums for now. Try a I–V–vi–IV progression with your left hand, one chord per bar, four bars total.",
      task: "play a simple I-V-vi-IV chord progression on piano, one chord per bar",
    },
    bass: {
      title: "Add left-hand root notes",
      detail: "Under each chord, play just the root note in a lower octave. That's your bass for now.",
      task: "add simple left-hand root notes under the chord progression",
    },
    music: {
      title: "Add a right-hand melody",
      detail: "Hum or pick out a simple melody with your right hand over the chords. A few notes repeated is a real start.",
      task: "add a simple right-hand piano melody over the chords",
    },
  },
  ambient: {
    groove: {
      title: "Start a slow pad instead of drums",
      detail: "Hold one chord on a soft pad or synth for four to eight bars. Let it swell in slowly rather than starting sharp.",
      task: "start a slow evolving pad holding one chord for background/game music",
    },
    bass: {
      title: "Add a low sustained note",
      detail: "One long, low note under the pad is enough — it doesn't need to move.",
      task: "add one low sustained bass note under the pad",
    },
    music: {
      title: "Add a simple melodic texture",
      detail: "A soft, sparse melody or arpeggio on top. It should sit in the background, not demand attention.",
      task: "add a soft sparse melody or arpeggio over the pad",
    },
  },
  "existing-idea": {
    groove: {
      title: "Build the groove your idea already implies",
      detail: "Listen back to what you have once, then add drums that match the feel it already has — don't start from a generic pattern.",
      task: "add a drum groove that matches the feel of the idea I already have",
    },
    bass: {
      title: "Add a bass line that fits",
      detail: "Two or three repeating notes that follow your kick and support the melody you already have.",
      task: "add a bass line that fits the existing idea and follows the kick",
    },
    music: {
      title: "Round out the melody you already have",
      detail: "Fill in any unfinished parts of the melody, or add one supporting layer around it.",
      task: "round out or add one supporting layer to the melody I already have",
    },
  },
  generic: {
    groove: {
      title: "Set up a simple 4-bar loop",
      detail: "Kick on beats 1 and 3, snare on 2 and 4, hi-hats on every half beat. Loop it and listen.",
      task: "set up a simple 4-bar drum loop — kick on 1 and 3, snare on 2 and 4, hats on every half beat",
    },
    bass: {
      title: "Add a bass line",
      detail: "Two or three repeating notes that follow the kick is enough for a first pass.",
      task: "add a simple bass line that follows the kick",
    },
    music: {
      title: "Add one melody or loop",
      detail: "One keys, synth, or loop layer on top. Keep it simple — one clear idea is enough.",
      task: "add one simple melody or loop on top of the beat",
    },
  },
};

export function buildMove(index: number, ctx: { goal: string; tool: Tool; profile: Profile; lastNote?: string }): Move {
  const content = PROFILE_CONTENT[ctx.profile];
  const isExisting = ctx.profile === "existing-idea";

  switch (index) {
    case 0:
      return isExisting
        ? {
            index, stage: "idea",
            title: "Open what you already have",
            detail: "Open the project, voice memo, or file where this idea already lives, and play it once, start to finish, so it's fresh.",
            copyText: assistantPrompt(ctx, "pick up a song idea I already started"),
          }
        : {
            index, stage: "idea",
            title: "Set up a simple project",
            detail: `${toolPrefix(ctx.tool)}create a new project and set the tempo to 90 BPM — a comfortable starting speed you can change any time.`,
            copyText: assistantPrompt(ctx, "start a new project and set a comfortable tempo"),
          };
    case 1:
      return { index, stage: "groove", title: content.groove.title, detail: `${toolPrefix(ctx.tool)}${content.groove.detail[0].toLowerCase()}${content.groove.detail.slice(1)}`, copyText: assistantPrompt(ctx, content.groove.task) };
    case 2:
      return { index, stage: "bass", title: content.bass.title, detail: content.bass.detail, copyText: assistantPrompt(ctx, content.bass.task) };
    case 3:
      return { index, stage: "music", title: content.music.title, detail: content.music.detail, copyText: assistantPrompt(ctx, content.music.task) };
    case 4:
      return {
        index, stage: "arrange",
        title: "Arrange a beginning, middle, and end",
        detail: "Intro: sparse, just one or two elements. Middle: everything together. End: strip parts back out. 30–60 seconds total is a real first track.",
        copyText: assistantPrompt(ctx, "arrange what I have into a beginning, middle, and end, 30 to 60 seconds"),
      };
    case 5:
      return {
        index, stage: "finish",
        title: "Listen back start to finish",
        detail: "Play it all the way through once. Notice what feels good and what feels empty — nothing to fix yet, just listen.",
        copyText: assistantPrompt(ctx, "tell me what to listen for on a first full playback"),
      };
    default:
      return {
        index, stage: "finish",
        title: "Export the audio",
        detail: `${toolPrefix(ctx.tool)}export or bounce the track as an MP3 or WAV, and save it where you can find it.`,
        copyText: assistantPrompt(ctx, "export or bounce this to a real MP3 or WAV file"),
      };
  }
}

// ---------------------------------------------------------------------------
// The session record — one active session at a time.
// ---------------------------------------------------------------------------

export interface LogEntry {
  stepIndex: number;
  note: string;
  at: string;
}

export const MUSIC_SESSION_VERSION = 1;

export interface MusicSessionV1 {
  version: 1;
  id: string;
  goal: string;
  tool: Tool;
  profile: Profile;
  stepIndex: number;
  log: LogEntry[];
  createdAt: string;
  updatedAt: string;
  finishedAt: string | null;
}

let counter = 0;
export function sessionUid(): string {
  counter += 1;
  return `${Date.now().toString(36)}-${counter.toString(36)}-${Math.random().toString(36).slice(2, 7)}`;
}

export function startSession(goal: string, tool: Tool, now?: string): MusicSessionV1 {
  const at = now ?? new Date().toISOString();
  return {
    version: 1,
    id: sessionUid(),
    goal: goal.trim(),
    tool,
    profile: detectProfile(goal),
    stepIndex: 0,
    log: [],
    createdAt: at,
    updatedAt: at,
    finishedAt: null,
  };
}

export function currentMove(session: MusicSessionV1): Move {
  const lastNote = session.log[session.log.length - 1]?.note;
  return buildMove(session.stepIndex, { goal: session.goal, tool: session.tool, profile: session.profile, lastNote });
}

export function isFinished(session: MusicSessionV1): boolean {
  return session.finishedAt !== null || session.stepIndex >= TOTAL_MOVES;
}

/** Records what happened and moves to the next step. A blank note is valid — "done" needs no explanation. */
export function advance(session: MusicSessionV1, note: string, now?: string): MusicSessionV1 {
  if (isFinished(session)) return session;
  const at = now ?? new Date().toISOString();
  const nextIndex = session.stepIndex + 1;
  return {
    ...session,
    stepIndex: nextIndex,
    log: [...session.log, { stepIndex: session.stepIndex, note: note.trim(), at }],
    updatedAt: at,
    finishedAt: nextIndex >= TOTAL_MOVES ? at : null,
  };
}

export interface Progress {
  stage: MusicStage;
  stageIndex: number;
  stageCount: number;
  moveIndex: number;
  moveCount: number;
}

export function progress(session: MusicSessionV1): Progress {
  const idx = Math.min(session.stepIndex, TOTAL_MOVES - 1);
  const move = buildMove(idx, { goal: session.goal, tool: session.tool, profile: session.profile });
  return {
    stage: move.stage,
    stageIndex: STAGE_ORDER.indexOf(move.stage),
    stageCount: STAGE_ORDER.length,
    moveIndex: session.stepIndex,
    moveCount: TOTAL_MOVES,
  };
}

// ---------------------------------------------------------------------------
// Stuck help — deterministic, tool-aware, never a guess dressed as fact.
// ---------------------------------------------------------------------------

const STUCK_BY_TOOL: Record<Tool, string> = {
  bandlab: "Look for the \"+\" button to add a new track, then choose an instrument or the Beat Maker.",
  garageband: "Track menu → New Track, then choose Drummer or a Software Instrument.",
  ableton: "Use the browser panel on the left — drag an instrument or Drum Rack onto a new MIDI track.",
  "fl-studio": "Open the Channel Rack (F6) and add or browse instruments from there.",
  logic: "Track menu → New Track → Software Instrument, then pick a patch.",
  ardour: "Ardour is mainly a recording and mixing tool — it may need an instrument plugin added to a MIDI track first.",
  mpc: "Load a program onto a track, then tap pads or keys to trigger sounds.",
  other: "Look for \"Add Track\" or a \"+\" button, then choose an instrument.",
  unsure: "Look for \"Add Track\" or a \"+\" button in your app, then choose an instrument.",
};

export function stuckHelp(tool: Tool): string[] {
  return [
    STUCK_BY_TOOL[tool],
    "If sound isn't working: check the tab or app isn't muted, and click inside the project once — some tools block audio until you interact with the page.",
    "Paste what you're seeing below and keep going — the next move will adjust.",
  ];
}

// ---------------------------------------------------------------------------
// Safe parse — never destroy an existing session on a bad read.
// ---------------------------------------------------------------------------

function str(v: unknown, fallback = ""): string {
  return typeof v === "string" ? v : fallback;
}
function num(v: unknown, fallback = 0): number {
  return typeof v === "number" && Number.isFinite(v) ? v : fallback;
}
function oneOf<T extends string>(v: unknown, allowed: readonly T[], fallback: T): T {
  return typeof v === "string" && (allowed as readonly string[]).includes(v) ? (v as T) : fallback;
}

export function parseSession(v: unknown): MusicSessionV1 | null {
  if (!v || typeof v !== "object") return null;
  const o = v as Record<string, unknown>;
  if (typeof o.id !== "string" || !o.id) return null;

  const goal = str(o.goal);
  return {
    version: 1,
    id: o.id,
    goal,
    tool: oneOf(o.tool, TOOLS, "unsure"),
    profile: oneOf(o.profile, ["reggae", "hiphop", "piano", "ambient", "existing-idea", "generic"] as const, detectProfile(goal)),
    stepIndex: Math.max(0, Math.min(TOTAL_MOVES, num(o.stepIndex))),
    log: Array.isArray(o.log)
      ? o.log.flatMap((e): LogEntry[] => {
          if (!e || typeof e !== "object") return [];
          const x = e as Record<string, unknown>;
          return [{ stepIndex: num(x.stepIndex), note: str(x.note), at: str(x.at, new Date().toISOString()) }];
        })
      : [],
    createdAt: str(o.createdAt, new Date().toISOString()),
    updatedAt: str(o.updatedAt, new Date().toISOString()),
    finishedAt: typeof o.finishedAt === "string" ? o.finishedAt : null,
  };
}
