// Music UI surface: the owner rejected the old static "First project"
// nine-row checklist and the repeated, useless "in your tool" phrasing.
// These tests read the actual component source (same technique as
// EngineSystem.test.ts) so a future edit can't quietly bring either back.
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const studio = readFileSync(join(__dirname, "MusicStudio.tsx"), "utf8");
const session = readFileSync(join(__dirname, "MusicSession.tsx"), "utf8");
const combined = studio + "\n" + session;

describe("Music starts from intent, not the old checklist", () => {
  it("no longer renders the OnboardingFlow / music.engine beginner checklist", () => {
    expect(studio).not.toMatch(/OnboardingFlow/);
    expect(studio).not.toMatch(/music\.engine/);
    expect(combined).not.toMatch(/Pick a drum kit/);
    expect(combined).not.toMatch(/Make a 4-bar drum pattern/);
  });

  it("the primary screen asks what the creator wants to make and what they're using", () => {
    expect(session).toMatch(/What do you want to make/);
    expect(session).toMatch(/What are you using/);
    expect(session).toMatch(/Start making/);
  });

  it("never repeats the bare 'in your tool' phrasing", () => {
    expect(combined.toLowerCase()).not.toContain("in your tool");
  });

  it("offers a real copy action and a paste-back path", () => {
    expect(session).toMatch(/Copy/);
    expect(session).toMatch(/navigator\.clipboard\.writeText/);
    expect(session).toMatch(/What happened/);
  });

  it("shows one next move, not a full checklist, while a session is active", () => {
    expect(session).toMatch(/Do this next/);
  });

  it("offers a stuck path that doesn't force a step to be marked done", () => {
    expect(session).toMatch(/I&apos;m stuck|I'm stuck/);
  });

  it("supports resetting to start something new", () => {
    expect(session).toMatch(/Start something new/);
  });

  it("never claims a fake save-to-library/build action", () => {
    expect(combined).not.toMatch(/Save to (Build|Library)/);
  });

  it("never claims audio or instructions were generated by AI", () => {
    expect(combined.toLowerCase()).not.toMatch(/ai[- ]generated|generated by ai|written by an? ai/);
  });
});
