import styles from "./ready.module.css";

// Evidence and feature boundaries: docs/ready-to-build-project-evidence.md.
const projects = [
  {
    name: "CrossHeartPray",
    href: "https://crossheartpray.com",
    what: "A place to read Scripture, follow a Bible reading plan, and pray.",
    helped: "Building the reading-plan interface, progress tracking, and tests.",
    sources: "Stored Bible text and reading-plan files. The code also supports YouVersion’s developer connection for translations enabled for the application.",
    matters: "The reader retrieves existing Scripture. It does not ask AI to invent a verse for each visitor.",
  },
  {
    name: "TheDJCares",
    href: "https://thedjcares.com",
    what: "A curated player for Christian music, videos, podcasts, and sermons.",
    helped: "Building and fixing playback controls, volume handling, and the player interface.",
    sources: "An approved media catalog, with YouTube, Apple Music, and Spotify players or links. Code selects from that catalog.",
    matters: "Browsing and playback do not need AI to invent songs or links. An optional AI feature can interpret a listening request; it still selects from approved content.",
  },
  {
    name: "iDontCry",
    href: "https://idontcry.com/sports",
    what: "Games and family tools, including a Sports Desk for following teams, schedules, and reported results.",
    helped: "Improving the Sports Desk’s pages, team navigation, and presentation of schedules and results.",
    sources: "Stored sports records, school EventLink calendars for schedules, and selected school and college athletics pages for published information.",
    matters: "The desk reads collected records rather than asking AI to invent scores. EventLink supplies schedules, not scores; missing results stay unconfirmed.",
  },
  {
    name: "WatchedNotWatched",
    href: "https://watchednotwatched.com",
    what: "Find movies, shows, and books, and keep track of what you have watched or read.",
    helped: "Building book search and detail pages, improving loading reliability, and adding tests.",
    sources: "Open Library for books; TMDB for movies and TV when configured, with TVmaze as a television fallback. Saved choices help organize your library.",
    matters: "Search retrieves provider records instead of generating titles. AI-assisted recommendations are a separate, controlled feature—not a requirement for each page view.",
  },
];

export default function RealProjects() {
  return (
    <section id="real-projects" className={styles.section} aria-labelledby="real-projects-heading">
      <div className={styles.sectionIntro}>
        <span className="kicker">From our own build history</span>
        <h2 id="real-projects-heading">AI helped build them. The data comes from somewhere real.</h2>
        <p>These are not imaginary demos generated by a chatbot. The websites in our own build history were created by using AI as a development partner, while the actual content, links, schedules, books, scores, and other information come from code, public APIs, official developer connections, open data, and trusted source websites.</p>
      </div>

      <div className={styles.truthCallout}>
        <h3>AI can help write the code. It does not have to be the source of truth.</h3>
        <p>The builder may use AI. The product does not have to be powered by AI.</p>
      </div>

      <ol className={styles.trustFlow} aria-label="From idea to a useful website">
        {["Idea", "AI-assisted development", "Code and trusted connections", "Useful live website"].map((step, i) => (
          <li key={step}><span className={styles.number}>0{i + 1}</span><strong>{step}</strong>{i < 3 && <span className={styles.flowArrow} aria-hidden="true">→</span>}</li>
        ))}
      </ol>

      <div className={styles.costModel}>
        <h3>Use AI to build. Keep everyday visits simple.</h3>
        <ul>
          <li>AI’s main role in the build process is to help plan, write, debug, test, and improve the software.</li>
          <li>The finished websites do not need an expensive AI request every time a visitor opens a page. Many pages can be served as normal web pages with ordinary hosting.</li>
          <li>Data can come from official feeds, open-data or open-source APIs, public developer connections, structured source files, or carefully selected trusted sources. An API is simply a way for one service to request information from another.</li>
          <li>AI can remain optional for special features rather than becoming a required cost for every page view.</li>
        </ul>
        <p>That can mean no or little ongoing AI cost for ordinary browsing. Hosting, storage, data providers, and optional AI features may still have costs.</p>
      </div>

      <div className={styles.projectEvidenceGrid}>
        {projects.map(project => (
          <article className={styles.projectEvidenceCard} key={project.name}>
            <h3>{project.name}</h3>
            <p>{project.what}</p>
            <dl>
              <div><dt>AI helped with:</dt><dd>{project.helped}</dd></div>
              <div><dt>Built on:</dt><dd>{project.sources}</dd></div>
              <div><dt>Why it matters:</dt><dd>{project.matters}</dd></div>
            </dl>
            <a className={styles.textLink} href={project.href}>Visit {project.name}{project.name === "iDontCry" ? " Sports Desk" : ""} <span aria-hidden="true">↗</span></a>
          </article>
        ))}
      </div>

      <div className={styles.note}>
        <strong>Useful software, without an AI API bill for every visit.</strong>
        <p>This is how a small creator can build useful websites without paying for an AI API on every visitor request. The intelligence is in the design, the code, the source selection, and the workflow—not in making up information.</p>
      </div>
      <p className={styles.sourceNote}>Source availability and API terms vary by project and must be checked before building. A working connection is not a promise of free access, unlimited use, or permission to republish everything it returns.</p>
    </section>
  );
}
